### ISSUE TITLE
Frontend improvements

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-javascript#613]
This is a work in progress, feel free to edit it to add/remove things

### Proposals

- [ ] Remove redundant packages: merge `@appsignal/core` and `@appsignal/types` into `@appsignal/javascript`.
- [ ] Implement missing features such as custom data ([support issue](https://github.com/appsignal/support/issues/295))
- [ ] Improve error reporting
  - [ ] Report the underlying error when reporting an uncaught promise rejection, instead of `UncaughtPromiseRejectionError`.
  - [ ] Report the action in which an error takes place (for example, for a React component, attempt to report the component name)

### Existing issues
 
- [ ] https://github.com/appsignal/appsignal-javascript/issues/533 -- We should consider whether we want to implement this. Is there really an use case for initialising AppSignal multiple times? And would there be a benefit, such as making AppSignal easier to use, if we expose it in the global object?
- [ ] https://github.com/appsignal/appsignal-javascript/issues/486 -- Since we don't support web vitals metrics via Next.js in the Node.js 3.x integration, this could be a nice way to bring support for it back.
- [ ] https://github.com/appsignal/appsignal-javascript/issues/527 -- This would bring the integration's internal logging in line with that of our other integrations, and give our users more control over what is logged by AppSignal. It would also provide a workaround for https://github.com/appsignal/appsignal-javascript/issues/297.

**Comment by tombruijn** [comment]
Looks like a good idea 👍

**Comment by matsimitsu** [comment]
Would be nice to support the metrics too, since we already expose an endpoint for it.
